-- Migration 010: Add action_type to proactive_artifacts
-- Phase 3: Level 1 draft artifacts need to be distinguishable from analysis artifacts
-- analysis = default Level 0 (markdown insight)
-- draft     = Level 1 (code fix file generated by rawos)

PRAGMA user_version = 10;

ALTER TABLE proactive_artifacts ADD COLUMN action_type TEXT NOT NULL DEFAULT 'analysis';

CREATE INDEX IF NOT EXISTS idx_proactive_artifacts_action ON proactive_artifacts(user_id, action_type, created_at DESC);
